# Generated by Django 3.2.7 on 2021-09-10 06:42

import datetime
from django.db import migrations
from django.utils.timezone import utc
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=datetime.datetime(2021, 9, 10, 6, 42, 56, 244578, tzinfo=utc), upload_to='profile_pic'),
            preserve_default=False,
        ),
    ]
