# Generated by Django 3.2.7 on 2021-09-10 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraccount_last_matched_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='last_detected_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'last_detected_image',
                'verbose_name_plural': 'last_detected_images',
            },
        ),
    ]
