# Generated by Django 3.2.7 on 2021-09-10 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_last_detected_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='last_detected_images',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 10, 11, 24, 14, 716408, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
