# Generated by Django 3.2.7 on 2021-09-11 04:48

from django.db import migrations
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_last_detected_images_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=users.models.wrapper),
        ),
    ]
