# Generated by Django 3.2.7 on 2021-09-11 04:50

from django.db import migrations
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_useraccount_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_matched_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=users.models.last_matched_wrapper),
        ),
    ]
