# Generated by Django 3.2.7 on 2021-09-25 11:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_useraccount_last_matched_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_matched_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
