version: "3.8"
services:
  django:
    build: .
    container_name: django
    # command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    command: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
