# Generated by Django 3.2.7 on 2021-09-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20210911_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='user',
            new_name='presentStudents',
        ),
    ]
