# Generated by Django 3.2.7 on 2021-09-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_alter_attendence_presentstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encodings', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
