# Generated by Django 3.2.7 on 2021-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_faceencoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceencoding',
            name='classNames',
            field=models.TextField(blank=True, null=True),
        ),
    ]
