# Generated by Django 3.2.7 on 2021-09-26 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0006_faceencoding_classnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceencoding',
            name='encodings',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
